### ISSUE TITLE
Error, audit and service control queue overides

### ISSUE THREAD

**Issue by JacobSearle** [SzymonPobiega/ServiceControl.TransportAdapter#1]
The transport adapter uses the default names for the audit, error and SC queues. Would it be possible to expose the ability to override these?

**Comment by SzymonPobiega** [comment]
@JacobSearle this has been addressed in 0.2.0 release. Because the number of config properties grew up significantly I decided to extract a separate configuration class. This will prevent users from setting the queue names after `Start`ing the adapter. Sorry for the inconvenience.
